version: '2'

services:
  node:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: npm start
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      # - "8888:80"
    # volumes:
    #   - nodejs
    links:
      - node
    volumes_from:
      - node
