version: '2'

services:
  sailjs:
    build: ./sailjs
  nginx:
    build: ./docker/nginx
    ports:
      - "1337:80"
      # - "8888:80"
    # volumes:
    #   - nodejs
    links:
      - sailjs
    volumes_from:
      - sailjs
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ./mongodb:/data/db

