FROM nginx:stable

COPY nginx.conf /etc/nginx/nginx.conf
# RUN apt-get update && apt-get install vim -y

# RUN rm -rf /etc/nginx/conf.d/default.conf

# COPY ./etc/web.conf /etc/nginx/conf.d/web.conf
# COPY ./etc/global/php-fpm.conf /etc/nginx/global/php-fpm.conf